In [8]:
from sklearn.datasets import load_iris
import numpy as np

# Ambil data iris
iris = load_iris()
X = iris.data  # hanya fitur, tanpa label

In [20]:
import numpy as np
from sklearn.datasets import load_iris

# Ambil data iris
iris = load_iris()
X = iris.data  # data fitur
n_samples = X.shape[0]
n_features = X.shape[1]
n_clusters = 3  # karena iris ada 3 kelas
m = 2.0  # fuzzifier
epsilon = 0.01
max_iter = 100

# Fungsi jarak Euclidean
def euclidean_distance(x, v):
    return np.linalg.norm(x - v)

# Inisialisasi keanggotaan U
U = np.random.dirichlet(np.ones(n_clusters), size=n_samples).T

for iteration in range(max_iter):
    U_old = U.copy()

    # Hitung pusat kluster
    V = np.zeros((n_clusters, n_features))
    for i in range(n_clusters):
        um = U[i] ** m
        V[i] = np.dot(um, X) / np.sum(um)

    # Update U
    for i in range(n_clusters):
        for k in range(n_samples):
            denom = 0
            for j in range(n_clusters):
                dist_i = euclidean_distance(X[k], V[i])
                dist_j = euclidean_distance(X[k], V[j])
                dist_i = max(dist_i, 1e-10)  # hindari pembagian 0
                dist_j = max(dist_j, 1e-10)
                denom += (dist_i / dist_j) ** (2 / (m - 1))
            U[i][k] = 1 / denom

    # Konvergensi
    if np.linalg.norm(U - U_old) < epsilon:
        break

# Ambil label dominan
labels = np.argmax(U, axis=0)

# Tampilkan hasil
print("Pusat kluster:\n", V)
print("\nLabel hasil FCM (0, 1, 2):\n", labels)

Pusat kluster:
 [[5.00396363 3.41413849 1.48273472 0.25351006]
 [5.88792667 2.76070677 4.36248206 1.39655767]
 [6.77379377 3.05202741 5.64526371 2.05295983]]

Label hasil FCM (0, 1, 2):
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 2 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 2 2 2 2 1 2 2 2 2
 2 2 1 2 2 2 2 2 1 2 1 2 1 2 2 1 1 2 2 2 2 2 1 2 2 2 2 1 2 2 2 1 2 2 2 1 2
 2 1]


In [10]:
from sklearn.metrics import adjusted_rand_score

true_labels = iris.target
ari = adjusted_rand_score(true_labels, labels)
print("\nAdjusted Rand Index:", ari)


Adjusted Rand Index: 0.7294203486015404


In [18]:
import numpy as np
from sklearn.datasets import load_iris

# Ambil data iris
iris = load_iris()
X = iris.data  # data fitur
n_samples = X.shape[0]
n_features = X.shape[1]
n_clusters = 3  # karena iris ada 3 kelas
m = 2.0  # fuzzifier
epsilon = 0.01
max_iter = 100

# Fungsi jarak Euclidean
def euclidean_distance(x, v):
    return np.linalg.norm(x - v)

# Inisialisasi keanggotaan U
U = np.random.dirichlet(np.ones(n_clusters), size=n_samples).T

for iteration in range(max_iter):
    U_old = U.copy()

    # Hitung pusat kluster
    V = np.zeros((n_clusters, n_features))
    for i in range(n_clusters):
        um = U[i] ** m
        V[i] = np.dot(um, X) / np.sum(um)

    # Update U
    for i in range(n_clusters):
        for k in range(n_samples):
            denom = 0
            for j in range(n_clusters):
                dist_i = euclidean_distance(X[k], V[i])
                dist_j = euclidean_distance(X[k], V[j])
                dist_i = max(dist_i, 1e-10)  # hindari pembagian 0
                dist_j = max(dist_j, 1e-10)
                denom += (dist_i / dist_j) ** (2 / (m - 1))
            U[i][k] = 1 / denom

    # Konvergensi
    if np.linalg.norm(U - U_old) < epsilon:
        break

# Ambil label dominan
labels = np.argmax(U, axis=0)

# Tampilkan hasil
print("Pusat kluster:\n", V)
print("\nLabel hasil FCM (0, 1, 2):\n", labels)

Pusat kluster:
 [[5.00396374 3.41413615 1.48273854 0.25351178]
 [5.88797478 2.76072409 4.36255302 1.39659444]
 [6.77385442 3.05204498 5.64533882 2.05298857]]

Label hasil FCM (0, 1, 2):
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 2 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 2 2 2 2 1 2 2 2 2
 2 2 1 2 2 2 2 2 1 2 1 2 1 2 2 1 1 2 2 2 2 2 1 2 2 2 2 1 2 2 2 1 2 2 2 1 2
 2 1]
