Fuzzy C-Mean 

Fuzzy C-Means (FCM) adalah salah satu algoritma clustering yang termasuk dalam keluarga fuzzy clustering. Berbeda dengan algoritma seperti K-Means yang bersifat hard clustering (setiap data hanya boleh masuk ke satu cluster), FCM bersifat soft clusterin. fuzzy c-means adalah kasus khusus dari K-meansketika fungsi probabilitas yang digunakan hanyalah 1 jika titik data paling dekat dengan suatu sentroid dan 0 jika tidak.

Kelebihan:

-Bisa menangani data yang tidak bisa dipisah secara tegas.

-Lebih fleksibel dibanding K-Means.

Langkah-langkah Fuzzy C-Mean :
1. Inisialisasi jumalah cluster C, nilai M dan matriks keanggotaan U
2. Iterasi sampai konvergen :
    - Hitung pusat cluster C
    - Update matriks keanggotaan Uij
    - Hitung fungsi Objektif

In [1]:
import numpy as np

# Data (x1, x2)
data = np.array([
    [1, 2],
    [2, 3],
    [3, 4],
    [6, 7],
    [7, 8]
], dtype=float)

# Jumlah cluster dan parameter m
C = 2
m = 2  # fuzziness

# Inisialisasi keanggotaan (baris = data, kolom = cluster)
U = np.array([
    [0.5, 0.5],
    [0.7, 0.3],
    [0.8, 0.2],
    [0.7, 0.3],
    [0.6, 0.4]
])

def update_centroids(U, data, m):
    um = U ** m
    centroids = []
    for j in range(C):
        numerator = np.sum((um[:, j].reshape(-1, 1)) * data, axis=0)
        denominator = np.sum(um[:, j])
        centroids.append(numerator / denominator)
    return np.array(centroids)

def update_membership(data, centroids, m):
    n = data.shape[0]
    U_new = np.zeros((n, C))
    for i in range(n):
        for j in range(C):
            denom_sum = 0
            for k in range(C):
                dist_ij = np.linalg.norm(data[i] - centroids[j]) + 1e-10  # tambah epsilon agar tidak div 0
                dist_ik = np.linalg.norm(data[i] - centroids[k]) + 1e-10
                ratio = dist_ij / dist_ik
                denom_sum += ratio ** (2 / (m - 1))
            U_new[i][j] = 1 / denom_sum
    return U_new

# Iterasi FCM sebanyak 2 kali
for iteration in range(2):
    print(f"\n🌀 Iterasi {iteration + 1}")
    centroids = update_centroids(U, data, m)
    print("Centroid:", centroids)

    U = update_membership(data, centroids, m)
    print("Keanggotaan (U):\n", np.round(U, 4))

# Output akhir
print("\n✅ Centroid akhir:\n", np.round(centroids, 4))
print("\n✅ Matriks keanggotaan akhir:\n", np.round(U, 4))


🌀 Iterasi 1
Centroid: [[3.86098655 4.86098655]
 [3.50793651 4.50793651]]
Keanggotaan (U):
 [[0.4345 0.5655]
 [0.3963 0.6037]
 [0.2582 0.7418]
 [0.5758 0.4242]
 [0.5531 0.4469]]

🌀 Iterasi 2
Centroid: [[4.60336854 5.60336854]
 [3.20743845 4.20743845]]
Keanggotaan (U):
 [[0.2729 0.7271]
 [0.177  0.823 ]
 [0.0165 0.9835]
 [0.7999 0.2001]
 [0.7146 0.2854]]

✅ Centroid akhir:
 [[4.6034 5.6034]
 [3.2074 4.2074]]

✅ Matriks keanggotaan akhir:
 [[0.2729 0.7271]
 [0.177  0.823 ]
 [0.0165 0.9835]
 [0.7999 0.2001]
 [0.7146 0.2854]]


In [1]:
pip install scikit-fuzzy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 920.8/920.8 kB 38.2 MB/s eta 0:00:00

[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
import skfuzzy as fuzz
import matplotlib.pyplot as plt

# Data dari kamu (x1, x2)
data = np.array([
    [1, 2],
    [2, 3],
    [3, 4],
    [6, 7],
    [7, 8]
])

# Transpose karena cmeans butuh dimensi (fitur x sampel)
data_T = data.T

# Parameter
n_clusters = 2
m = 2.0         # fuzziness
error = 0.005   # toleransi
maxiter = 1000  # maksimal iterasi

# Jalankan FCM
cntr, u, u0, d, jm, p, fpc = fuzz.cluster.cmeans(
    data_T, n_clusters, m, error, maxiter, init=None, seed=42)

# cntr = koordinat pusat cluster
# u = matriks keanggotaan akhir (shape: n_clusters x n_samples)

# Transpose hasil keanggotaan agar sebaris dengan data
u_transposed = u.T

# Tampilkan hasil
print("📌 Centroid:\n", np.round(cntr, 4))
print("\n📌 Matriks Keanggotaan:\n", np.round(u_transposed, 4))

# Tentukan cluster dengan keanggotaan tertinggi
cluster_labels = np.argmax(u_transposed, axis=1) + 1  # +1 agar cluster dimulai dari 1
for i, label in enumerate(cluster_labels):
    print(f"Data ke-{i+1} masuk ke Cluster {label}")


📌 Centroid:
 [[1.9676 2.9676]
 [6.4882 7.4882]]

📌 Matriks Keanggotaan:
 [[9.699e-01 3.010e-02]
 [9.999e-01 1.000e-04]
 [9.195e-01 8.050e-02]
 [1.440e-02 9.856e-01]
 [1.020e-02 9.898e-01]]
Data ke-1 masuk ke Cluster 1
Data ke-2 masuk ke Cluster 1
Data ke-3 masuk ke Cluster 1
Data ke-4 masuk ke Cluster 2
Data ke-5 masuk ke Cluster 2


In [3]:
import numpy as np

# Data
X = np.array([
    [1, 2],
    [2, 3],
    [3, 4],
    [6, 7],
    [7, 8]
])

# Derajat awal (U) dimensi: n data × c cluster
U = np.array([
    [0.5, 0.5],
    [0.7, 0.3],
    [0.8, 0.2],
    [0.7, 0.3],
    [0.6, 0.4]
])

m = 2  # fuzzy exponent
epsilon = 0.000001  # ambang konvergensi
max_iter = 100

def compute_centroids(X, U, m):
    Um = U ** m
    centroids = []
    for j in range(U.shape[1]):
        num = np.sum((Um[:, j].reshape(-1, 1)) * X, axis=0)
        den = np.sum(Um[:, j])
        centroids.append(num / den)
    return np.array(centroids)

def update_membership(X, centroids, m):
    n = X.shape[0]
    c = centroids.shape[0]
    U_new = np.zeros((n, c))
    for i in range(n):
        for j in range(c):
            dist_ij = np.linalg.norm(X[i] - centroids[j]) + 1e-10  # avoid zero
            sum_term = 0
            for k in range(c):
                dist_ik = np.linalg.norm(X[i] - centroids[k]) + 1e-10
                sum_term += (dist_ij / dist_ik) ** (2 / (m - 1))
            U_new[i, j] = 1 / sum_term
    return U_new

# Iterasi hingga konvergen
iteration = 0
while True:
    print(f"\n=== ITERASI {iteration + 1} ===")
    centroids = compute_centroids(X, U, m)
    print("Centroid:")
    for idx, c in enumerate(centroids):
        print(f"  C{idx+1}: {c}")
    U_new = update_membership(X, centroids, m)
    print("Keanggotaan Baru (U):\n", np.round(U_new, 4))

    # Cek konvergensi
    if iteration > 0:
        centroid_shift = np.linalg.norm(centroids - old_centroids)
        print(f"Perubahan centroid: {centroid_shift:.6f}")
        if centroid_shift < epsilon or iteration >= max_iter:
            print("\n✅ Konvergen tercapai.")
            break

    old_centroids = centroids
    U = U_new
    iteration += 1


=== ITERASI 1 ===
Centroid:
  C1: [3.86098655 4.86098655]
  C2: [3.50793651 4.50793651]
Keanggotaan Baru (U):
 [[0.4345 0.5655]
 [0.3963 0.6037]
 [0.2582 0.7418]
 [0.5758 0.4242]
 [0.5531 0.4469]]

=== ITERASI 2 ===
Centroid:
  C1: [4.60336854 5.60336854]
  C2: [3.20743845 4.20743845]
Keanggotaan Baru (U):
 [[0.2729 0.7271]
 [0.177  0.823 ]
 [0.0165 0.9835]
 [0.7999 0.2001]
 [0.7146 0.2854]]
Perubahan centroid: 1.132634

=== ITERASI 3 ===
Centroid:
  C1: [6.00971594 7.00971594]
  C2: [2.43836418 3.43836418]
Keanggotaan Baru (U):
 [[0.0762 0.9238]
 [0.0118 0.9882]
 [0.0337 0.9663]
 [1.     0.    ]
 [0.955  0.045 ]]
Perubahan centroid: 2.266843

=== ITERASI 4 ===
Centroid:
  C1: [6.45806457 7.45806457]
  C2: [2.03271073 3.03271073]
Keanggotaan Baru (U):
 [[3.460e-02 9.654e-01]
 [1.000e-04 9.999e-01]
 [7.260e-02 9.274e-01]
 [9.868e-01 1.320e-02]
 [9.882e-01 1.180e-02]]
Perubahan centroid: 0.855069

=== ITERASI 5 ===
Centroid:
  C1: [6.48792764 7.48792764]
  C2: [1.97473482 2.97473482]
Ke